variables:
  IMAGE_NAME: registry.gitlab.com/roeidalal/blackjack
  IMAGE_TAG: "1.0"

stages:
  - "build"
  - "deploy_docker"

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy_docker
  image: centos
  before_script:
    - yum update && yum install -y docker && yum install -y docker-compose
    - systemctl start docker
  script:
    - docker pull $IMAGE_NAME:$IMAGE_TAG
    - docker tag $IMAGE_NAME:$IMAGE_TAG bj:latest
    - docker-compose up -d