build_image:
  image: docker
  before_script:
    - docker login registry.gitlab.com
  script:
    - docker build -t registry.gitlab.com/roeidalal/blackjack .
    - docker push registry.gitlab.com/roeidalal/blackjack
