variables:
  IMAGE_NAME: registry.gitlab.com/roeidalal/blackjack
  IMAGE_TAG: "1.0"

stages:
  - "build"
  - "deploy_docker"
  - "deploy_k8s"

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  when: manual

deploy_docker:
  stage: deploy_docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker pull $IMAGE_NAME:$IMAGE_TAG
    - docker tag $IMAGE_NAME:$IMAGE_TAG bj:latest
    - docker-compose up -d
  when: manual

deploy_k8s:
  stage: deploy_k8s
  script:
    - helm install blackjack blackjack
  when: manual
