apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}
spec:
  selector:
    app: {{ .Values.mongo.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.express.name }}
spec:
  selector:
    app: {{ .Values.express.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.express.port }}
      targetPort: {{ .Values.express.port }}
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  type: LoadBalancer